# Generated by Django 2.2.5 on 2019-11-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('existencias', models.IntegerField(default=0)),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('Bolsos para Hombres', 'Bolsos para hombres'), ('Bolsos para Mujeres', 'Bolsos para mujeres')], default='Bolsos para Mujeres', max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'ACTIVO'), ('Deshabilitado', 'DESHABILITADO')], default='', max_length=15)),
            ],
        ),
    ]
