# Generated by Django 2.2.5 on 2019-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Bolsos para Hombres', 'Bolsos para hombres'), ('Bolsos para Mujeres', 'Bolsos para mujeres')], default='Bolsos para Mujeres', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Deshabilitado', 'DESHABILITADO')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=20),
        ),
    ]
