# Generated by Django 2.2.5 on 2019-11-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencias',
        ),
    ]
