# Generated by Django 2.2.5 on 2019-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20191124_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockMaximo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stockMinimo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
