# Generated by Django 2.2.5 on 2019-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20191123_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0),
        ),
    ]
