# Generated by Django 2.2.5 on 2019-11-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permiso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombre', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=240, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permiso.Permiso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
