# Generated by Django 2.2.5 on 2019-11-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacionInventario', '0002_actualizacioninventario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacioninventario',
            name='fecha',
        ),
    ]
