# Generated by Django 2.2.5 on 2019-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorInicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorinicial',
            name='estadoCuenta',
            field=models.CharField(choices=[('A', 'ACREDEDORA'), ('D', 'DEUDORA'), ('S', 'SALDADA'), ('P', 'PATRIMONIO')], default='S', max_length=1),
        ),
    ]
