# Generated by Django 2.2.5 on 2019-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorInicial', '0002_valorinicial_estadocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorinicial',
            name='estadoCuenta',
            field=models.CharField(choices=[('A', 'ACREEEDORA'), ('D', 'DEUDORA'), ('S', 'SALDADA'), ('P', 'PATRIMONIO')], default='S', max_length=1),
        ),
    ]
