# Generated by Django 2.2.5 on 2019-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorInicial', '0003_auto_20191018_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorinicial',
            name='saldo',
            field=models.FloatField(null=True),
        ),
    ]
