# Generated by Django 2.2.5 on 2019-11-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('saldo', models.FloatField()),
                ('modificaInventario', models.BooleanField()),
                ('estadoCuenta', models.CharField(choices=[('A', 'ACREEEDORA'), ('D', 'DEUDORA'), ('S', 'SALDADA')], default='S', max_length=1)),
                ('tipo', models.CharField(choices=[('D', 'DEBE'), ('H', 'HABER')], default='D', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'ACTIVA'), ('D', 'DESHABILITADA')], default='A', max_length=1)),
                ('cuentaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.Cuenta')),
            ],
        ),
    ]
