# Generated by Django 2.2.5 on 2019-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_auto_20191015_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='estadoCuenta',
            field=models.CharField(choices=[('A', 'ACREEEDORA'), ('D', 'DEUDORA'), ('S', 'SALDADA')], default='S', max_length=1),
        ),
    ]
