# Generated by Django 2.2.5 on 2019-11-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_auto_20191018_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigoCuenta',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
