# Generated by Django 2.2.5 on 2019-10-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('idTransaccionInv', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
                ('costoTotal', models.FloatField()),
                ('detalle', models.CharField(max_length=150)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.Kardex')),
            ],
        ),
    ]
