# Generated by Django 2.2.5 on 2019-11-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('idTransaccionInv', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidadComprada', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
                ('factura', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('I', 'INVENTARIO INICIAL'), ('C', 'COMPRA'), ('V', 'VENTA'), ('DC', 'DEVOLUCION DE COMPRA'), ('DV', 'DEVOLUCION DE VENTA')], default='I', max_length=2)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.Kardex')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
