# Generated by Django 2.2.5 on 2019-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioninventario',
            name='tipo',
            field=models.CharField(choices=[('I', 'INVENTARIO INICIAL'), ('C', 'COMPRA'), ('V', 'VENTA'), ('DC', 'DEVOLUCION DE COMPRA'), ('DV', 'DEVOLUCION DE VENTA')], default='I', max_length=2),
        ),
    ]
