# Generated by Django 2.2.5 on 2019-11-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccionInventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccioninventario',
            old_name='cantidadComprada',
            new_name='cantidadTransaccion',
        ),
        migrations.RenameField(
            model_name='transaccioninventario',
            old_name='costoUnitario',
            new_name='valorUnitario',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='kardex',
        ),
    ]
