# Generated by Django 2.2.5 on 2019-11-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20191124_2154'),
        ('transaccionInventario', '0002_transaccioninventario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccioninventario',
            old_name='cantidad',
            new_name='cantidadTransaccion',
        ),
        migrations.RenameField(
            model_name='transaccioninventario',
            old_name='costoTotal',
            new_name='valorUnitario',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='costoUnitario',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='kardex',
        ),
        migrations.AddField(
            model_name='transaccioninventario',
            name='factura',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccioninventario',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
            preserve_default=False,
        ),
    ]
