# Generated by Django 2.2.5 on 2019-11-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_existencias'),
        ('transaccionInventario', '0002_transaccioninventario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccioninventario',
            old_name='cantidad',
            new_name='cantidadComprada',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='costoTotal',
        ),
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='detalle',
        ),
        migrations.AddField(
            model_name='transaccioninventario',
            name='cantidadSobrante',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccioninventario',
            name='factura',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccioninventario',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
            preserve_default=False,
        ),
    ]
