# Generated by Django 2.2.5 on 2019-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccionInventario', '0003_auto_20191124_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccioninventario',
            name='tipo',
            field=models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENTA'), ('DC', 'DEVOLUCION DE COMPRA'), ('DV', 'DEVOLUCION DE VENTA')], default='I', max_length=2),
        ),
    ]
