# Generated by Django 2.2.5 on 2019-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccionInventario', '0003_auto_20191118_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioninventario',
            name='cantidadSobrante',
        ),
    ]
