# Generated by Django 2.2.5 on 2019-11-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=250)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('saldoParcial', models.FloatField(null=True)),
                ('tipo', models.CharField(choices=[('C', 'CARGAR'), ('A', 'ABONAR')], default='C', max_length=1)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.Cuenta')),
            ],
        ),
    ]
