# Generated by Django 2.2.5 on 2019-10-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0003_auto_20191015_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=250)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('C', 'CARGAR'), ('A', 'ABONAR')], default='C', max_length=1)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.Cuenta')),
            ],
        ),
    ]
