# Generated by Django 2.2.5 on 2019-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='saldoParcial',
            field=models.FloatField(null=True),
        ),
    ]
