# Generated by Django 2.2.5 on 2019-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='Existencias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kardex',
            name='stockMaximo',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kardex',
            name='stockMinimo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kardex',
            name='unidad',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kardex',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
