# Generated by Django 2.2.5 on 2019-11-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaperiodo',
            old_name='costoUnitario',
            new_name='valorUnitario',
        ),
        migrations.AddField(
            model_name='lineaperiodo',
            name='compraAsociada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
