# Generated by Django 2.2.5 on 2019-11-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_auto_20191118_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='Existencias',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='valor',
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('existenciaFinal', models.IntegerField()),
                ('saldoFinal', models.FloatField()),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.Kardex')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPeriodo',
            fields=[
                ('idLineaPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tipoTransaccion', models.CharField(max_length=3)),
                ('cantidadSobrante', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
                ('cantidadEntrada', models.IntegerField()),
                ('valorEntrada', models.FloatField()),
                ('cantidadSalida', models.IntegerField()),
                ('valorSalida', models.FloatField()),
                ('cantidadExistencia', models.IntegerField()),
                ('valorExistencia', models.FloatField()),
                ('comprobacion', models.FloatField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.Periodo')),
            ],
        ),
    ]
