# Generated by Django 2.2.5 on 2019-11-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccionInventario', '0003_auto_20191124_2154'),
        ('kardex', '0002_auto_20191124_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaperiodo',
            name='transaccionInvAsociada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transaccionInventario.TransaccionInventario'),
            preserve_default=False,
        ),
    ]
