# Generated by Django 2.2.5 on 2019-11-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_lineaperiodo_transaccioninvasociada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='stockMaximo',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='stockMinimo',
        ),
    ]
