# Generated by Django 2.2.5 on 2019-11-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_auto_20191123_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
