# Generated by Django 2.2.5 on 2019-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombreContribuyente', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=17)),
                ('nrc', models.CharField(max_length=5)),
                ('giro', models.CharField(max_length=30)),
            ],
        ),
    ]
